/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        // Light theme colors
        'primary-light': '#4A6FA5',
        'secondary-light': '#22D3EE',
        'tertiary-light': '#D3545D',
        'alternate-light': '#E0E3E7',
        'text-primary-light': '#14181B',
        'text-secondary-light': '#57636C',
        'bg-primary-light': '#F7F8FA',
        'bg-secondary-light': '#FFFFFF',
        'icon-light': '#57636C',
        'divider-light': '#E0E3E7',
        'hover-light': '#00000008',
        
        // Dark theme colors
        'primary-dark': '#4A6FA5',
        'secondary-dark': '#2C3E50',
        'tertiary-dark': '#D3545D',
        'alternate-dark': '#262D34',
        'text-primary-dark': '#FFFFFF',
        'text-secondary-dark': '#95A1AC',
        'bg-primary-dark': '#1C1E26',
        'bg-secondary-dark': '#14181B',
        'icon-dark': '#95A1AC',
        'divider-dark': '#262D34',
        'hover-dark': '#FFFFFF08',
        
        // Feedback colors
        'success-bg-light': '#E7F7EE',
        'success-text-light': '#1B4332',
        'success-border-light': '#2D6A4F',
        'warning-bg-light': '#FEF3C7',
        'warning-text-light': '#92400E',
        'warning-border-light': '#D97706',
        'error-bg-light': '#FEE2E2',
        'error-text-light': '#991B1B',
        'error-border-light': '#DC2626',
        'info-bg-light': '#E0F2FE',
        'info-text-light': '#075985',
        'info-border-light': '#0284C7',
        
        'success-bg-dark': '#064E3B',
        'success-text-dark': '#ECFDF5',
        'success-border-dark': '#059669',
        'warning-bg-dark': '#451A03',
        'warning-text-dark': '#FEF3C7',
        'warning-border-dark': '#D97706',
        'error-bg-dark': '#450A0A',
        'error-text-dark': '#FEE2E2',
        'error-border-dark': '#DC2626',
        'info-bg-dark': '#082F49',
        'info-text-dark': '#E0F2FE',
        'info-border-dark': '#0284C7',
      },
      fontFamily: {
        'inter-regular': ['Inter_400Regular'],
        'inter-semibold': ['Inter_600SemiBold'],
        'inter-bold': ['Inter_700Bold'],
      },
      fontSize: {
        // Mantendo a mesma escala do design system
        'display-lg': ['48px', { lineHeight: '56px', fontWeight: '700' }],
        'display-md': ['40px', { lineHeight: '48px', fontWeight: '700' }],
        'display-sm': ['36px', { lineHeight: '44px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'title': ['28px', { lineHeight: '32px', fontWeight: '700' }],
        'subtitle': ['18px', { lineHeight: '24px', fontWeight: '700' }],
        'label-lg': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'body': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-semibold': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'small': ['12px', { lineHeight: '16px', fontWeight: '400' }],
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        '2xl': '48px',
        '3xl': '64px',
      },
      borderRadius: {
        'none': '0',
        'xs': '2px',
        'sm': '4px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        '2xl': '24px',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}; 